-- MySQL Script generated by MySQL Workbench
-- Tue Oct 17 19:52:40 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e22000229_db2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e22000229_db2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e22000229_db2` DEFAULT CHARACTER SET utf8mb4 ;
USE `e22000229_db2` ;

-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_COMPTE_CPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_COMPTE_CPT` (
  `cpt_id` INT NOT NULL AUTO_INCREMENT,
  `cpt_mail` VARCHAR(255) NOT NULL,
  `cpt_pseudo` VARCHAR(255) NOT NULL,
  `cpt_password` CHAR(64) NOT NULL,
  `cpt_nom` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  `cpt_prenom` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_general_ci' NULL,
  `cpt_statut` CHAR(1) NOT NULL,
  `cpt_role` CHAR(1) NOT NULL,
  PRIMARY KEY (`cpt_id`),
  UNIQUE INDEX `mail_UNIQUE` (`cpt_mail` ASC),
  UNIQUE INDEX `pseudo_UNIQUE` (`cpt_pseudo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_ACTUALITE_ACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_ACTUALITE_ACT` (
  `act_id` INT NOT NULL AUTO_INCREMENT,
  `act_titre` VARCHAR(255) NOT NULL,
  `act_date` DATE NOT NULL,
  `act_contenu` TEXT NOT NULL,
  `act_statut` CHAR(1) NOT NULL,
  `cpt_id` INT NOT NULL,
  PRIMARY KEY (`act_id`),
  INDEX `AtualiteUtilisateurFK1_idx` (`cpt_id` ASC),
  CONSTRAINT `AtualiteUtilisateurFK`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22000229_db2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_PARTICIPANT_PNT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_PARTICIPANT_PNT` (
  `pnt_id` INT NOT NULL AUTO_INCREMENT,
  `pnt_mail` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`pnt_id`),
  UNIQUE INDEX `mail_UNIQUE` (`pnt_mail` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_RESSOURCE_RES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_RESSOURCE_RES` (
  `res_id` INT NOT NULL AUTO_INCREMENT,
  `res_type` VARCHAR(255) NOT NULL,
  `res_chemin` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`res_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_ETAPE_ETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_ETAPE_ETA` (
  `eta_id` INT NOT NULL AUTO_INCREMENT,
  `eta_intitule` VARCHAR(255) NOT NULL,
  `eta_statut` CHAR(1) NOT NULL,
  `eta_question` VARCHAR(255) NOT NULL,
  `eta_reponse` VARCHAR(45) NOT NULL,
  `res_id` INT NOT NULL,
  `sce_id` INT NOT NULL,
  `eta_prochaine_id` INT NULL,
  PRIMARY KEY (`eta_id`),
  INDEX `EtapeRessourceFK1_idx` (`res_id` ASC),
  INDEX `EtapeScenarioFK1_idx` (`sce_id` ASC),
  INDEX `EtapeEtapeFK1_idx` (`eta_prochaine_id` ASC),
  CONSTRAINT `EtapeRessourceFK`
    FOREIGN KEY (`res_id`)
    REFERENCES `e22000229_db2`.`T_RESSOURCE_RES` (`res_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `EtapeEtapeFK`
    FOREIGN KEY (`eta_prochaine_id`)
    REFERENCES `e22000229_db2`.`T_ETAPE_ETA` (`eta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_SCENARIO_SCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_SCENARIO_SCE` (
  `sce_id` INT NOT NULL AUTO_INCREMENT,
  `sce_intitule` VARCHAR(45) NOT NULL,
  `sce_statut` CHAR(1) NOT NULL,
  `sce_code` CHAR(8) NOT NULL,
  `cpt_id` INT NOT NULL,
  `res_id` INT NULL,
  `eta_id` INT NULL,
  PRIMARY KEY (`sce_id`),
  INDEX `ScfenarioUtilisateurFK1_idx` (`cpt_id` ASC),
  INDEX `ScenarioRessourceFK2_idx` (`res_id` ASC),
  INDEX `ScenarioEtapeFK_idx` (`eta_id` ASC),
  CONSTRAINT `ScenarioUtilisateurFK`
    FOREIGN KEY (`cpt_id`)
    REFERENCES `e22000229_db2`.`T_COMPTE_CPT` (`cpt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ScenarioRessourceFK`
    FOREIGN KEY (`res_id`)
    REFERENCES `e22000229_db2`.`T_RESSOURCE_RES` (`res_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ScenarioEtapeFK`
    FOREIGN KEY (`eta_id`)
    REFERENCES `e22000229_db2`.`T_ETAPE_ETA` (`eta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_INDICE_IND`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_INDICE_IND` (
  `ind_id` INT NOT NULL AUTO_INCREMENT,
  `ind_texte` VARCHAR(255) NOT NULL,
  `ind_lien` VARCHAR(255) NOT NULL,
  `ind_niveau` INT NOT NULL,
  `eta_id` INT NOT NULL,
  PRIMARY KEY (`ind_id`),
  INDEX `EtapeIndiceFK1_idx` (`eta_id` ASC),
  CONSTRAINT `EtapeIndiceFK`
    FOREIGN KEY (`eta_id`)
    REFERENCES `e22000229_db2`.`T_ETAPE_ETA` (`eta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e22000229_db2`.`T_PARTICIPATION_PON`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e22000229_db2`.`T_PARTICIPATION_PON` (
  `pnt_id` INT NOT NULL AUTO_INCREMENT,
  `sce_id` INT NOT NULL,
  `pon_date_reussite` DATE NOT NULL,
  `pon_date_derniere_participation` DATE NOT NULL,
  `pon_difficulte_max_reussie` INT NOT NULL,
  PRIMARY KEY (`pnt_id`, `sce_id`),
  INDEX `ParticipationScenarioFK2_idx` (`sce_id` ASC),
  CONSTRAINT `ParticipationParticipantFK`
    FOREIGN KEY (`pnt_id`)
    REFERENCES `e22000229_db2`.`T_PARTICIPANT_PNT` (`pnt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ParticipationScenarioFK`
    FOREIGN KEY (`sce_id`)
    REFERENCES `e22000229_db2`.`T_SCENARIO_SCE` (`sce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE T_ETAPE_ETA ADD CONSTRAINT `EtapeScenarioFK` FOREIGN KEY (`sce_id`) REFERENCES `e22000229_db2`.`T_SCENARIO_SCE` (`sce_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
